[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
avax-mainnet = "${AVAX_MAINNET_RPC_URL}"


[etherscan]
fuji = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/gakonst/foundry/tree/master/config